# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

unlist_cpp <- function(list) {
    .Call(`_mixnhreg_unlist_cpp`, list)
}

grad_optim_cpp <- function(X, G) {
    .Call(`_mixnhreg_grad_optim_cpp`, X, G)
}

get_parameter_cpp <- function(X, link, inverse) {
    .Call(`_mixnhreg_get_parameter_cpp`, X, link, inverse)
}

get_parameter_optim_cpp <- function(X, x, links, N, K) {
    .Call(`_mixnhreg_get_parameter_optim_cpp`, X, x, links, N, K)
}

get_parameter_boost_cpp <- function(X, x, links, N, K) {
    .Call(`_mixnhreg_get_parameter_boost_cpp`, X, x, links, N, K)
}

get_basefits_cpp <- function(X, G, N, K) {
    .Call(`_mixnhreg_get_basefits_cpp`, X, G, N, K)
}

update_coef_cpp <- function(y, X, x, B, links, loss_fun, nu, N, K) {
    .Call(`_mixnhreg_update_coef_cpp`, y, X, x, B, links, loss_fun, nu, N, K)
}

boost_noncylcic_cpp <- function(y, X, x, links, loss_fun, grad_fun, nll_fun, nu, maxit, N, K) {
    .Call(`_mixnhreg_boost_noncylcic_cpp`, y, X, x, links, loss_fun, grad_fun, nll_fun, nu, maxit, N, K)
}

get_loss_cv_cpp <- function(y, X, x, links, loss_fun, maxit, N, K) {
    .Call(`_mixnhreg_get_loss_cv_cpp`, y, X, x, links, loss_fun, maxit, N, K)
}

root_finder <- function(location, scale, weight, p, xmin, xmax, tol) {
    .Call(`_mixnhreg_root_finder`, location, scale, weight, p, xmin, xmax, tol)
}

dmixnorm_cpp <- function(x, location, scale, weight, log_p) {
    .Call(`_mixnhreg_dmixnorm_cpp`, x, location, scale, weight, log_p)
}

pmixnorm_cpp <- function(q, location, scale, weight, log_p, lower_tail) {
    .Call(`_mixnhreg_pmixnorm_cpp`, q, location, scale, weight, log_p, lower_tail)
}

qmixnorm_cpp <- function(p, location, scale, weight, log_p, lower_tail) {
    .Call(`_mixnhreg_qmixnorm_cpp`, p, location, scale, weight, log_p, lower_tail)
}

rmixnorm_cpp <- function(p, location, scale, weight) {
    .Call(`_mixnhreg_rmixnorm_cpp`, p, location, scale, weight)
}

logs_mixnorm_cpp <- function(x, location, scale, weight) {
    .Call(`_mixnhreg_logs_mixnorm_cpp`, x, location, scale, weight)
}

crps_mixnorm_cpp <- function(x, location, scale, weight) {
    .Call(`_mixnhreg_crps_mixnorm_cpp`, x, location, scale, weight)
}

grad_logs_mixnorm_cpp <- function(x, location, scale, weight) {
    .Call(`_mixnhreg_grad_logs_mixnorm_cpp`, x, location, scale, weight)
}

grad_crps_mixnorm_cpp <- function(x, location, scale, weight) {
    .Call(`_mixnhreg_grad_crps_mixnorm_cpp`, x, location, scale, weight)
}

